apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocis.fullname" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ocis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ocis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          #command: ["/usr/bin/ocis", "server"]
          command: ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
          #command: ["sleep", "infinity"]
          volumeMounts:
            - name: ocis-configfiles
              mountPath: /etc/ocis/
            - name: ocis-supervisord-conf
              mountPath: /etc/supervisord.conf
              subPath: supervisord.conf
            - name: ocis-supervisord-procs
              mountPath: /etc/supervisord.d
            - name: ocis-data
              mountPath: "{{ .Values.persistentVolume.mountPath }}"
              subPath: "{{ .Values.persistentVolume.subPath }}"
            - name: ocis-config
              mountPath: "/var/tmp/ocis/.config/"
          env:
          {{- range $name, $value := .Values.env }}
            - name: "{{ $name }}"
              value: "{{ $value }}"
          {{- end }}
          {{- if .Values.extraEnv }}
            {{- toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: ocis-configfiles
          configMap:
            name: {{ include "ocis.fullname" . }}-configfiles
            defaultMode: 0777
        - name: ocis-supervisord-conf
          configMap:
            name: {{ include "ocis.fullname" . }}-supervisord-conf
        - name: ocis-supervisord-procs
          configMap:
            name: {{ include "ocis.fullname" . }}-supervisord-procs
        - name: ocis-config
          configMap:
            name: {{ include "ocis.fullname" . }}-config
        - name: ocis-data
        {{- if .Values.persistentVolume.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.persistentVolume.existingClaim }}{{ .Values.persistentVolume.existingClaim }}{{- else }}{{ template "ocis.fullname" . }}{{- end }}
        {{- else }}
          emptyDir:
          {{- if .Values.emptyDir.sizeLimit }}
            sizeLimit: {{ .Values.emptyDir.sizeLimit }}
          {{- else }}
            {}
          {{- end -}}
        {{- end -}}
