{{- if and .Values.ingress.enabled .Values.ingress.exposeIdp -}}
{{- $fullName := include "ocis.fullname" . -}}
{{- $idpPort := .Values.services.idp.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
        {{- range tuple "/.well-known" "/konnect" "/signin" }}
          - path: {{ . }}
            pathType: Prefix
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $idpPort }}
        {{- end }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}

---
{{- if and .Values.ingress.enabled .Values.ingress.grpc -}}
{{- $fullName := include "ocis.fullname" . -}}
{{- $grpcServicePort := .Values.service.grpc.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}-grpc
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
  {{- if .Values.ingress.grpc.annotations }}
  annotations:
    {{- range $key, $value := .Values.ingress.grpc.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.grpc.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $grpcServicePort }}
  {{- end }}
  {{- if .Values.ingress.grpc.tls }}
  tls:
    {{- toYaml .Values.ingress.grpc.tls | nindent 4 }}
  {{- end }}
{{- end }}
